// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz85dtSN1C4O9FCGL1zPKwfPq7wAooJ_M',
    appId: '1:167454263064:web:50226d51f00b04d10a806d',
    messagingSenderId: '167454263064',
    projectId: 'my-medicine-box-97fa3',
    authDomain: 'my-medicine-box-97fa3.firebaseapp.com',
    storageBucket: 'my-medicine-box-97fa3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0IZKn3Xl3COTi4qVrAWL3reIVEBhtvs8',
    appId: '1:167454263064:android:ed03a097487e40240a806d',
    messagingSenderId: '167454263064',
    projectId: 'my-medicine-box-97fa3',
    storageBucket: 'my-medicine-box-97fa3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrfShqg8kMORzFXiy8xjM2jm_pD3kjd4s',
    appId: '1:167454263064:ios:73f286d8d73ebfa10a806d',
    messagingSenderId: '167454263064',
    projectId: 'my-medicine-box-97fa3',
    storageBucket: 'my-medicine-box-97fa3.firebasestorage.app',
    iosBundleId: 'com.example.myMedicineBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrfShqg8kMORzFXiy8xjM2jm_pD3kjd4s',
    appId: '1:167454263064:ios:73f286d8d73ebfa10a806d',
    messagingSenderId: '167454263064',
    projectId: 'my-medicine-box-97fa3',
    storageBucket: 'my-medicine-box-97fa3.firebasestorage.app',
    iosBundleId: 'com.example.myMedicineBox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz85dtSN1C4O9FCGL1zPKwfPq7wAooJ_M',
    appId: '1:167454263064:web:bb327cf4e82e75fc0a806d',
    messagingSenderId: '167454263064',
    projectId: 'my-medicine-box-97fa3',
    authDomain: 'my-medicine-box-97fa3.firebaseapp.com',
    storageBucket: 'my-medicine-box-97fa3.firebasestorage.app',
  );
}
