// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE3qw1vOtX76R8bCHOFQ1gN8D9_YkR7zI',
    appId: '1:576559200435:web:40c25368678de160d318c6',
    messagingSenderId: '576559200435',
    projectId: 'my-medicine-box-387c3',
    authDomain: 'my-medicine-box-387c3.firebaseapp.com',
    storageBucket: 'my-medicine-box-387c3.firebasestorage.app',
    measurementId: 'G-TZ5KB1CDPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYTyVp2U1xHJGpHzyhww2KasHIll77WXs',
    appId: '1:576559200435:android:2b209af58856f473d318c6',
    messagingSenderId: '576559200435',
    projectId: 'my-medicine-box-387c3',
    storageBucket: 'my-medicine-box-387c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIt0cH8-7cXGTfFBy411ymO58gbcumPFo',
    appId: '1:576559200435:ios:d064841f10b73616d318c6',
    messagingSenderId: '576559200435',
    projectId: 'my-medicine-box-387c3',
    storageBucket: 'my-medicine-box-387c3.firebasestorage.app',
    iosClientId: '576559200435-vjdsl7v2jm7pgqb1n9tg9m6pn1gr2fsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.myMedicineBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIt0cH8-7cXGTfFBy411ymO58gbcumPFo',
    appId: '1:576559200435:ios:d064841f10b73616d318c6',
    messagingSenderId: '576559200435',
    projectId: 'my-medicine-box-387c3',
    storageBucket: 'my-medicine-box-387c3.firebasestorage.app',
    iosClientId: '576559200435-vjdsl7v2jm7pgqb1n9tg9m6pn1gr2fsb.apps.googleusercontent.com',
    iosBundleId: 'com.example.myMedicineBox',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE3qw1vOtX76R8bCHOFQ1gN8D9_YkR7zI',
    appId: '1:576559200435:web:5494ebc60eadef3bd318c6',
    messagingSenderId: '576559200435',
    projectId: 'my-medicine-box-387c3',
    authDomain: 'my-medicine-box-387c3.firebaseapp.com',
    storageBucket: 'my-medicine-box-387c3.firebasestorage.app',
    measurementId: 'G-03EXFR94LE',
  );

}